installing_message = "Reminder: yuzu is an <b>experimental</b> emulator. Stuff will break!"
hide_advanced = true

[[packages]]
name = "yuzu"
description = "The linux build of yuzu."
default = true
    [packages.source]
    name = "github"
    match = "^yuzu-linux-[0-9]*-[0-9a-f]*.tar.xz$"
        [packages.source.config]
        repo = "yuzu-emu/yuzu-mainline"

    [[packages.shortcuts]]
    name = "yuzu"
    relative_path = "./yuzu"
    description = "Launch yuzu"
